### ISSUE TITLE
Synchronisation down with vivaldi

### ISSUE THREAD

**Issue by dJeePe** [fastaddons/GroupSpeedDial#125]
hello,

since some days, synchronisation is down with the addons on vivaldi (it works well for me with firefox, chrome and edge)
it used to works
Here is the log :

Environment: Group Speed Dial 18.3; info: arch: x86-64, nacl_arch: x86-64, os: win; {};
Pixel ratio: 1.2000000476837158
Running time: 7.9s
Stats: 0 - 20,17,14,23,18,21,18,12,17,15,15,34,15,23
{"indexedDB":"9.2MB","storageLocal":"56.0KB","storageSync":"85.4KB","localStorage":"17.4KB"}
Runtime logs:
2022-03-15T20:26:48.268Z     1ms, bc - logger service started
2022-03-15T20:26:48.333Z    65ms, bc - isAndroidPromise
2022-03-15T20:26:48.407Z    74ms, bc - DB: opened
2022-03-15T20:26:48.407Z     0ms, bc - DB.promise
2022-03-15T20:26:52.281Z  3874ms, bc - DEFAULT_GROUPS_PROMISE
2022-03-15T20:26:52.659Z   378ms, bc - OPTIONS_PROMISE
2022-03-15T20:26:52.660Z     1ms, bc - incognito migration
2022-03-15T20:26:52.699Z    39ms, bc - async sync module
2022-03-15T20:26:52.955Z   256ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:26:53.200Z   245ms, bc - First tab starts loading.
2022-03-15T20:26:53.272Z    72ms, bc - DB query START: group.getAll(4)
2022-03-15T20:26:53.281Z     9ms, bc - DB query END: group.getAll(4)
2022-03-15T20:26:55.026Z  1745ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:26:59.079Z  4053ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:27:07.160Z  8081ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:27:23.217Z 16057ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:27:55.271Z 32054ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:28:59.184Z 63913ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
2022-03-15T20:29:13.333Z 14149ms, bc - sync
null
{"errData":{"err":"network error"},"errText":"Error","status":0}
Error
    at d (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:13385)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:59776
    at R (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:60032)
    at async chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/background/background_gsd.js:2:58112
Persistent logs:

Can i give you something else ?

**Comment by dJeePe** [comment]
hello,

i had to change the extension settings :

it was "on click" and i change it for "all site"
here's a screenshot :

[image: image.png]

**Comment by fastaddons** [comment]
Hello,
So it works now?
I don't see a screenshot because you can't send images through the email reply - this conversation is on the web so when you reply to this notification email, it will write a comment here:
https://github.com/fastaddons/GroupSpeedDial/issues/125
But it will strip off some data like images and email addresses if you include any.

But I think I know what you mean, restricting domain access for my addon will indeed break synchronization and many other features, like thumbnails generation which requires all domains access.

**Comment by dJeePe** [comment]
yes, it works now.
thank you.

you can see the image here : https://user-images.githubusercontent.com/85245954/158548658-f1bfeca3-b4a1-48ba-9493-30468f1d5ea9.png
