### ISSUE TITLE
Error getting thumbnails: [object Event]

### ISSUE THREAD

**Issue by ITGeekMonkeys** [fastaddons/GroupSpeedDial#156]
Error getting thumbnails: [object Event]
UnknownError,Internal error opening backing store for indexedDB.open.
Environment: Group Speed Dial 21.1; info: arch: x86-64, nacl_arch: x86-64, os: win; {};
Pixel ratio: 1
Running time: 0.02s
Stats: 0 - 56,41,49,100,77,49,56,45,83,14,5,4,4,41,11,52,4,55,7,10,33,4,11,24,12,3,7,2
{"indexedDB":"84.2MB","storageLocal":"199.8KB","storageSync":"52.2KB","localStorage":"52.4KB"}
Runtime logs:
2022-08-08T11:20:05.226Z     0ms, bc - logger service started
2022-08-08T11:20:05.238Z    12ms, bc - isAndroidPromise
2022-08-08T11:20:05.245Z     7ms, bc - store
2022-08-08T11:20:05.246Z     1ms, bc - OPTIONS_PROMISE
2022-08-08T11:20:08.602Z  3356ms, bc - First tab starts loading.
2022-08-08T11:20:10.642Z  2040ms, fr - db operation failed
UnknownError
Internal error opening backing store for indexedDB.open.
[object Event]
""
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at l.withDB (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:51754)
    at async l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:42707)
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)
2022-08-08T11:20:10.642Z     0ms, fr - [object Object]
undefined
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27375
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)
2022-08-08T11:20:52.636Z 41994ms, fr - db operation failed
UnknownError
Internal error opening backing store for indexedDB.open.
[object Event]
""
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at l.withDB (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:51754)
    at async l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:42707)
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)
2022-08-08T11:20:52.636Z     0ms, fr - [object Object]
undefined
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27375
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)
2022-08-08T11:21:36.703Z 44067ms, fr - db operation failed
UnknownError
Internal error opening backing store for indexedDB.open.
[object Event]
""
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at l.withDB (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:51754)
    at async l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:42707)
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)
2022-08-08T11:21:36.703Z     0ms, fr - [object Object]
undefined
Error
    at l (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:100828)
    at chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27375
    at async ue (chrome-extension://imfeikbeimbfpmgfkkmjekabdehiiajc/dial.js:1:27278)

**Device info:**
 - operating system: Windows 10 21H2 19044.1806
 - Browser and version: Brave v1.42.88 (Aug 6th, 2022)
 - GroupSpeedDial version: 21.1

**Additional info**
Add any other info about the problem here.
Happened immediately after updating to the latest version of Brave.

**Comment by fastaddons** [comment]
Hello,
Seems like the database can't be opened.
This is a browser error, usually restarting it or whole PC helps.
For more info, please check this article:
https://github.com/fastaddons/GroupSpeedDial/wiki/Fixing-broken-dials-page
